/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.86
 * Generated at: 2023-05-30 11:43:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.finProj;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.w3c.dom.Document;
import java.time.LocalDate;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class find_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("org.w3c.dom.Document");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".input-group {\r\n");
      out.write("	margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write(".mb-3 > .border-primary {\r\n");
      out.write("	border-color:#86b7fe!important;\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("	margin-right:10px;\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("    box-shadow: none!important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	LocalDate now = LocalDate.now();
	String ctryfrom = "";
	String ctryto = now.toString();
	String dfrom = now.toString();
	String dto = now.toString();
	try{
		Cookie[] cookies = request.getCookies();
		
		if(cookies != null) {
			for(int i=0; i< cookies.length; i++){
				if(cookies[i].getName().equals("countryfrom")){
					ctryfrom = cookies[i].getValue();
				} else if (cookies[i].getName().equals("countryto")){
					ctryto = cookies[i].getValue();
				} else if (cookies[i].getName().equals("datefrom")){
					dfrom = cookies[i].getValue();
				} else if (cookies[i].getName().equals("dateto")){
					dto = cookies[i].getValue();
				}
			}
		}else throw new Exception();
	}catch (Exception e){
		
	}
	

      out.write("\r\n");
      out.write("	<form action=\"./result.jsp\" method=\"post\" style=\"margin-bottom:30px; padding:10px\">\r\n");
      out.write("		<div class=\"input-group mb-3\">		\r\n");
      out.write("		  	<label class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" style=\"border-bottom-left-radius: 10px!important;border-top-left-radius: 10px!important;\" for=\"countryfrom\">출발지</label>\r\n");
      out.write("		  	<input type=\"text\" list=\"country-airport\" class=\"form-control border border-primary\" id=\"countryfrom\" placeholder=\"국가 또는 공항\"  style=\"text-transform: uppercase;\" name=\"countryfrom\" value=\"");
      out.print(ctryfrom);
      out.write("\"> \r\n");
      out.write("		  	<datalist id=\"country-airport\">\r\n");
      out.write("		    	");

					try{
						String id = "root";
						String password = "111111";
						String url = "jdbc:mysql://localhost:3306/jspdb_3315?characterEncoding=utf-8";
						
						Connection conn = null;
						PreparedStatement pstmt = null;
						ResultSet rs = null;
						//2. DB 연결
						conn = DriverManager.getConnection(url,id, password);
						
						//3. SQL문 완성
						String sql = "select * from country, airport where airport.country=country.countryname_en";
						pstmt = conn.prepareStatement(sql);
						
						//4. SQL문 실행(전송)
						rs = pstmt.executeQuery();
						int i = 1;
						while(rs.next()){
					
      out.write("		<option value=\"");
      out.print(rs.getString(4) );
      out.write("\" label=\"");
      out.print( rs.getString(2) );
      out.write(',');
      out.write(' ');
      out.print( rs.getString(3) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(7) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(8) );
      out.write("\" />\r\n");
      out.write("							");

							i++;
						}
						conn.close();
						pstmt.close();
						rs.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				
      out.write("\r\n");
      out.write("		  </datalist>\r\n");
      out.write("		  	<label class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" for=\"countryto\">도착지</label>\r\n");
      out.write("		  	<input type=\"text\" list=\"country-airport\" class=\"form-control border border-primary\" id=\"countryto\" placeholder=\"국가 또는 공항\"  style=\"text-transform: uppercase;\" name=\"countryto\"  value=\"");
      out.print(ctryto);
      out.write("\"> \r\n");
      out.write("		  	<datalist id=\"country-airport\">\r\n");
      out.write("		    	");

					try{
						String id = "root";
						String password = "111111";
						String url = "jdbc:mysql://localhost:3306/jspdb_3315?characterEncoding=utf-8";
						
						Connection conn = null;
						PreparedStatement pstmt = null;
						ResultSet rs = null;
						//2. DB 연결
						conn = DriverManager.getConnection(url,id, password);
						
						//3. SQL문 완성
						String sql = "select * from country, airport where airport.country=country.countryname_en";
						pstmt = conn.prepareStatement(sql);
						
						//4. SQL문 실행(전송)
						rs = pstmt.executeQuery();
						int i = 1;
						while(rs.next()){
					
      out.write("		<option value=\"");
      out.print(rs.getString(4) );
      out.write("\" label=\"");
      out.print( rs.getString(2) );
      out.write(',');
      out.write(' ');
      out.print( rs.getString(3) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(7) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(8) );
      out.write("\" />\r\n");
      out.write("							");

							i++;
						}
						conn.close();
						pstmt.close();
						rs.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				
      out.write("\r\n");
      out.write("		  </datalist>\r\n");
      out.write("		  <span class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" id=\"datefrom\">가는편</span>\r\n");
      out.write("		  \r\n");
      out.write("		  <input type=\"date\" class=\"form-control border border-primary\" id=\"datefrom\" name=\"datefrom\"  value=\"");
      out.print(dfrom );
      out.write("\" min=\"");
      out.print(now );
      out.write("\" maxlength=\"10\">\r\n");
      out.write("		  <span class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" id=\"dateto\">오는편</span>\r\n");
      out.write("		  <input type=\"date\" class=\"form-control border border-primary\"  value=\"");
      out.print(dto );
      out.write("\" min=\"");
      out.print(dfrom );
      out.write("\" id=\"dateto\" name=\"dateto\" style=\"border-bottom-right-radius: 10px!important;border-top-right-radius: 10px!important;\">	\r\n");
      out.write("		  \r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"d-grid gap-2 col-6 mx-auto\">\r\n");
      out.write("			  	<button class=\"btn btn-primary\" type=\"submit\">항공권 찾기</button>\r\n");
      out.write("			  	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
