/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.86
 * Generated at: 2023-06-04 16:09:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.finProj;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.w3c.dom.Document;
import java.time.LocalDate;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import finProj_flight.findResultDo;
import java.util.ArrayList;

public final class sort_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/finProj/find.jsp", Long.valueOf(1685879478000L));
    _jspx_dependants.put("/finProj/nav.jsp", Long.valueOf(1685322118000L));
    _jspx_dependants.put("/finProj/result2.jsp", Long.valueOf(1685894864000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("org.w3c.dom.Document");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("finProj_flight.findResultDo");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".btn-outline-light:hover{\r\n");
      out.write("    color: #0d6efd !important ;\r\n");
      out.write("}\r\n");
      out.write("/* point-color : #E3F321*/\r\n");
      out.write("</style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");
	String logout = request.getParameter("logout");

	//logout 변수에 값이 있으면, 리셋
	if(logout != null) {
		session.setAttribute("username", null);		
	}
	
	//세션에 저장되어 있는 id 값 읽어오기
	String username = (String)session.getAttribute("username");
	if(username == null) {
		username = " ";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <!-- <a class=\"navbar-brand\" href=\"#\">Navbar</a> -->\r\n");
      out.write("    \r\n");
      out.write("    <a class=\"navbar-brand\" href=\"./main.jsp\">\r\n");
      out.write("      <img src=\"./assets/trip1.png\" alt=\"\" width=\"35\" class=\"d-inline-block align-text-top\">\r\n");
      out.write("      JSP FLIGHTS\r\n");
      out.write("    </a>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"./main.jsp\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Link</a>\r\n");
      out.write("        </li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- <form class=\"d-flex\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("      </form> -->\r\n");
      out.write("      ");

      	if(username.equals(" ")){
	
      out.write("\r\n");
      out.write("			<input class=\"btn btn-outline-light\" type=\"button\" value=\"로그인\" onclick=\"location.href='loginFormBoot.jsp'\" style=\"margin-left: 20px;\"> \r\n");
      out.write("			<input class=\"btn btn-outline-light\" type=\"button\" value=\"회원가입\" onclick=\"location.href='registerFormBoot.jsp'\" style=\"margin-left: 20px;\"> \r\n");
      out.write("	");

      	} else {
	
      out.write("\r\n");
      out.write("      		<div style=\"color:white\">\r\n");
      out.write("      			");
      out.print(username );
      out.write(" 님  <input class=\"btn btn-outline-light\" type=\"button\" value=\"로그아웃\" onclick=\"location.href='main.jsp?logout=1'\" style=\"margin-left: 20px;\"> </div>\r\n");
      out.write("      		\r\n");
      out.write("	");

      	}
      
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".input-group {\r\n");
      out.write("	margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write(".mb-3 > .border-primary {\r\n");
      out.write("	border-color:#86b7fe!important;\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("	margin-right:10px;\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("    box-shadow: none!important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	LocalDate now = LocalDate.now();
	String ctryfrom = (String)session.getAttribute("countryfrom");
	String ctryto = (String)session.getAttribute("countryto");
	String dfrom = (String)session.getAttribute("datefrom");
	String dto = (String)session.getAttribute("dateto");
	if (ctryfrom == null) {
		ctryfrom = "";
	}
	if (ctryto == null) {
		ctryto = "";
	}
	if (dfrom == null) {
		dfrom = now.toString();		
	}
	if (dto == null) {
		dto = dfrom;		
	}
	

      out.write("\r\n");
      out.write("	<form action=\"./findProc.jsp\" method=\"post\" style=\"margin-bottom:30px; padding:10px\">\r\n");
      out.write("		<div class=\"input-group mb-3\">		\r\n");
      out.write("		  	<label class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" style=\"border-bottom-left-radius: 10px!important;border-top-left-radius: 10px!important;\" for=\"countryfrom\">출발지</label>\r\n");
      out.write("		  	<input type=\"text\" list=\"country-airport\" class=\"form-control border border-primary\" id=\"countryfrom\" placeholder=\"국가 또는 공항\"  style=\"text-transform: uppercase;\" name=\"countryfrom\" value=\"");
      out.print(ctryfrom);
      out.write("\"> \r\n");
      out.write("		  	<datalist id=\"country-airport\">\r\n");
      out.write("		    	");

					try{
						String id = "root";
						String password = "111111";
						String url = "jdbc:mysql://localhost:3306/jspdb_3315?characterEncoding=utf-8";
						
						Connection conn = null;
						PreparedStatement pstmt = null;
						ResultSet rs = null;
						//2. DB 연결
						conn = DriverManager.getConnection(url,id, password);
						
						//3. SQL문 완성
						String sql = "select * from country, airport where airport.country=country.countryname_en";
						pstmt = conn.prepareStatement(sql);
						
						//4. SQL문 실행(전송)
						rs = pstmt.executeQuery();
						int i = 1;
						while(rs.next()){
					
      out.write("		<option value=\"");
      out.print(rs.getString(4) );
      out.write("\" label=\"");
      out.print( rs.getString(2) );
      out.write(',');
      out.write(' ');
      out.print( rs.getString(3) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(7) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(8) );
      out.write("\" />\r\n");
      out.write("							");

							i++;
						}
						conn.close();
						pstmt.close();
						rs.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				
      out.write("\r\n");
      out.write("		  </datalist>\r\n");
      out.write("		  	<label class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" for=\"countryto\">도착지</label>\r\n");
      out.write("		  	<input type=\"text\" list=\"country-airport\" class=\"form-control border border-primary\" id=\"countryto\" placeholder=\"국가 또는 공항\"  style=\"text-transform: uppercase;\" name=\"countryto\"  value=\"");
      out.print(ctryto);
      out.write("\"> \r\n");
      out.write("		  	<datalist id=\"country-airport\">\r\n");
      out.write("		    	");

					try{
						String id = "root";
						String password = "111111";
						String url = "jdbc:mysql://localhost:3306/jspdb_3315?characterEncoding=utf-8";
						
						Connection conn = null;
						PreparedStatement pstmt = null;
						ResultSet rs = null;
						//2. DB 연결
						conn = DriverManager.getConnection(url,id, password);
						
						//3. SQL문 완성
						String sql = "select * from country, airport where airport.country=country.countryname_en";
						pstmt = conn.prepareStatement(sql);
						
						//4. SQL문 실행(전송)
						rs = pstmt.executeQuery();
						int i = 1;
						while(rs.next()){
					
      out.write("		<option value=\"");
      out.print(rs.getString(4) );
      out.write("\" label=\"");
      out.print( rs.getString(2) );
      out.write(',');
      out.write(' ');
      out.print( rs.getString(3) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(7) );
      out.write(',');
      out.write(' ');
      out.print(rs.getString(8) );
      out.write("\" />\r\n");
      out.write("							");

							i++;
						}
						conn.close();
						pstmt.close();
						rs.close();
					} catch (Exception e) {
						e.printStackTrace();
					}
				
      out.write("\r\n");
      out.write("		  </datalist>\r\n");
      out.write("		  <span class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" id=\"datefrom\">가는편</span>\r\n");
      out.write("		  \r\n");
      out.write("		  <input type=\"date\" class=\"form-control border border-primary\" id=\"datefrom\" name=\"datefrom\"  value=\"");
      out.print(dfrom );
      out.write("\" min=\"");
      out.print(now );
      out.write("\" maxlength=\"10\">\r\n");
      out.write("		  <span class=\"input-group-text bg-primary p-2 text-dark bg-opacity-10 border border-primary\" id=\"dateto\">오는편</span>\r\n");
      out.write("		  <input type=\"date\" class=\"form-control border border-primary\"  value=\"");
      out.print(dto );
      out.write("\" min=\"");
      out.print(dfrom );
      out.write("\" id=\"dateto\" name=\"dateto\" style=\"border-bottom-right-radius: 10px!important;border-top-right-radius: 10px!important;\">	\r\n");
      out.write("		  \r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"d-grid gap-2 col-6 mx-auto\">\r\n");
      out.write("			  	<button class=\"btn btn-primary\" type=\"submit\">항공권 찾기</button>\r\n");
      out.write("			  	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("th{\r\n");
      out.write("	text-align: center!important;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("	display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write(".btn-check:focus+.btn, .btn:focus, .btn-check:focus+.btn-outline-secondary, .btn-outline-secondary:focus, .btn-check:checked+.btn-outline-secondary:focus {\r\n");
      out.write("box-shadow: none!important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String sort = "takeofftime";

      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		");
      finProj_flight.findResultDo rdo = null;
      rdo = (finProj_flight.findResultDo) _jspx_page_context.getAttribute("rdo", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (rdo == null){
        rdo = new finProj_flight.findResultDo();
        _jspx_page_context.setAttribute("rdo", rdo, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\r\n");
        out.write("			");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("rdo"), request);
        out.write("\r\n");
        out.write("		");
      }
      out.write("\r\n");
      out.write("		");
      finProj_flight.findResultDao rdao = null;
      rdao = (finProj_flight.findResultDao) _jspx_page_context.getAttribute("rdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (rdao == null){
        rdao = new finProj_flight.findResultDao();
        _jspx_page_context.setAttribute("rdao", rdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("		<div class=\"fw-bolder fs-3\" style=\"display: flex;justify-content: space-between;align-items: flex-end;margin-bottom:20px\">출국편\r\n");
      out.write("		<form action=\"findProc.jsp\" class=\"btn-group btn-group-sm\" role=\"group\" aria-label=\"Basic radio toggle button group\" method=\"post\">\r\n");
      out.write("		  <input type=\"radio\" class=\"btn-check\" value=\"1\" name=\"sort1\" id=\"go1\" autocomplete=\"off\" checked>\r\n");
      out.write("		  <button type=\"submit\" class=\"btn btn-outline-secondary\" for=\"go1\" style=\"height:30px\">이른순</button>\r\n");
      out.write("		\r\n");
      out.write("		  <input type=\"radio\" class=\"btn-check\" value=\"2\" name=\"sort1\" id=\"go2\" autocomplete=\"off\">\r\n");
      out.write("		  <button type=\"submit\" class=\"btn btn-outline-secondary\" for=\"go2\" style=\"height:30px\">항공사순</button>\r\n");
      out.write("		\r\n");
      out.write("		  <input type=\"radio\" class=\"btn-check\" value=\"3\" name=\"sort1\" id=\"go3\" autocomplete=\"off\">\r\n");
      out.write("		  <button type=\"submit\" class=\"btn btn-outline-secondary\" for=\"go3\" style=\"height:30px\">짧은비행순</button>\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table border=\"1\" class=\"table table-hover\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 항공사 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 편명 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 출발 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 도착 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 비행시간 </th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");

		ArrayList<findResultDo> aList = rdao.getFlights(rdo.getCountryfrom(),rdo.getCountryto(),rdo.getDatefrom(),sort);
		ArrayList<findResultDo> bList = rdao.getFlights(rdo.getCountryto(),rdo.getCountryfrom(), rdo.getDateto(),sort);
		for(int i = 0; i< aList.size(); i++) {
			findResultDo rTemp = aList.get(i);

      out.write("\r\n");
      out.write("\r\n");
      out.write("			<tr height=\"60\" align=\"center\">\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print( rTemp.getAirline() );
      out.write("</td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print(rTemp.getFlightairline() );
      out.write(' ');
      out.print(rTemp.getFlightno() );
      out.write(" </td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print( rTemp.getFlightfrom() );
      out.write("</td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print( rTemp.getFlightto() );
      out.write(" </td>\r\n");
      out.write("				<td width=\"20%\"> \r\n");
      out.write("				");
      out.print(rTemp.getFlightdate() );
      out.write(" <br> ");
      out.print( rTemp.getTakeofftime() );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(rTemp.getLandingtime() );
      out.write(" </td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("		");

		}
	
      out.write("</tbody></table>\r\n");
      out.write("	\r\n");
      out.write("	<br><br><br>\r\n");
      out.write("		<div class=\"fw-bolder fs-3\" style=\"display: flex;justify-content: space-between;align-items: flex-end;margin-bottom:20px\">귀국편\r\n");
      out.write("			<form class=\"btn-group btn-group-sm\" role=\"group\" aria-label=\"Basic radio toggle button group\" method=\"post\">\r\n");
      out.write("			  <input type=\"radio\" class=\"btn-check\" value=\"1\" name=\"sort\" id=\"btnradio1\" autocomplete=\"off\" checked>\r\n");
      out.write("			  <label class=\"btn btn-outline-secondary\" for=\"btnradio1\" style=\"height:30px\">이른순</label>\r\n");
      out.write("			\r\n");
      out.write("			  <input type=\"radio\" class=\"btn-check\" value=\"2\" name=\"sort\" id=\"btnradio2\" autocomplete=\"off\">\r\n");
      out.write("			  <label class=\"btn btn-outline-secondary\" for=\"btnradio2\" style=\"height:30px\">항공사순</label>\r\n");
      out.write("			\r\n");
      out.write("			  <input type=\"radio\" class=\"btn-check\" value=\"3\" name=\"sort\" id=\"btnradio3\" autocomplete=\"off\">\r\n");
      out.write("			  <label class=\"btn btn-outline-secondary\" for=\"btnradio3\" style=\"height:30px\">짧은비행순</label>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table border=\"1\" class=\"table table-hover\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 항공사 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 편명 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 출발 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 도착 </th>\r\n");
      out.write("					<th width=\"20%\" scope=\"col\"> 비행시간 </th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");

		for(int i = 0; i< bList.size(); i++) {
			findResultDo rTemp = bList.get(i);

      out.write("\r\n");
      out.write("			<tr height=\"60\" align=\"center\">\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print( rTemp.getAirline() );
      out.write("</td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print(rTemp.getFlightairline() );
      out.write(' ');
      out.print(rTemp.getFlightno() );
      out.write(" </td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print( rTemp.getFlightfrom() );
      out.write("</td>\r\n");
      out.write("				<td width=\"20%\"> ");
      out.print(rTemp.getFlightto() );
      out.write(" </td>\r\n");
      out.write("				<td width=\"20%\"> \r\n");
      out.write("				");
      out.print(rTemp.getFlightdate() );
      out.write(" <br> ");
      out.print(rTemp.getTakeofftime() );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(rTemp.getLandingtime() );
      out.write(" </td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");

		}
	
      out.write("</tbody></table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
